# Generated by Django 5.2.4 on 2025-08-23 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'dollar kursi',
                'verbose_name_plural': 'dollar kursi',
            },
        ),
    ]
