# Generated by Django 5.2.4 on 2025-09-05 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymenttype_cashtransaction_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransactionFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kassa papkasi',
                'verbose_name_plural': 'Kassa papkalari',
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='finance.cashtransactionfolder'),
        ),
    ]
