# Generated by Django 5.2.4 on 2025-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cashtransactionfolder_cashtransaction_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='expence_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='income_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='total_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
