# Generated by Django 5.2.4 on 2025-09-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashtransaction_expence_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='expence_balance',
            new_name='expence_balance_usd',
        ),
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='income_balance',
            new_name='expence_balance_uzs',
        ),
        migrations.RenameField(
            model_name='cashtransaction',
            old_name='total_balance',
            new_name='income_balance_usd',
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='income_balance_uzs',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='total_balance_usd',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='total_balance_uzs',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
