# Generated by Django 5.2.4 on 2025-09-08 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0004_counterparty_status'),
        ('finance', '0006_typeincome'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd')], max_length=3)),
                ('price', models.PositiveBigIntegerField()),
                ('exchange_rate', models.PositiveBigIntegerField(default=0)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='finance/income/file/')),
                ('audit', models.CharField(max_length=200)),
                ('cash_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.cashtransaction')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='counterparty.counterparty')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.paymenttype')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='projects.project')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='projects.projectfolder')),
                ('type_income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finance.typeincome')),
            ],
            options={
                'verbose_name': 'kirim',
                'verbose_name_plural': 'kirimlar',
            },
        ),
    ]
