# Generated by Django 5.2.4 on 2025-09-08 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0004_counterparty_status'),
        ('finance', '0009_expencetype'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('exchange_rate', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('uzs', 'uzs')], max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('audit', models.CharField(blank=True, max_length=200, null=True)),
                ('cash_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expences', to='finance.cashtransaction')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences', to='counterparty.counterparty')),
                ('expence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences', to='finance.expencetype')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expences', to='finance.paymenttype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences', to='projects.project')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expences', to='projects.projectfolder')),
            ],
            options={
                'verbose_name': 'chiqim',
                'verbose_name_plural': 'chiqimlar',
            },
        ),
    ]
