# Generated by Django 5.2.4 on 2025-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_expence'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='total_usd',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='total_uzs',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='payment_type',
            field=models.ManyToManyField(blank=True, related_name='cash_transactions', to='finance.paymenttype'),
        ),
    ]
