# Generated by Django 5.2.4 on 2025-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_paymenttype_total_usd_paymenttype_total_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='file',
            field=models.FileField(blank=True, null=True, unique='finance/expence/files/', upload_to=''),
        ),
    ]
