# Generated by Django 5.2.4 on 2025-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_expence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='finance/expence/files/'),
        ),
    ]
