# Generated by Django 5.2.4 on 2025-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_expence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='exchange_rate',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
