# Generated by Django 5.2.4 on 2025-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_expence_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='expence_balance_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='expence_balance_uzs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='income_balance_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='income_balance_uzs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='total_balance_usd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='total_balance_uzs',
            field=models.BigIntegerField(default=0),
        ),
    ]
