# Generated by Django 5.2.4 on 2025-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_cashtransaction_expence_balance_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='exchange_rate',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
