# Generated by Django 5.2.4 on 2025-09-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_income_exchange_rate'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences', to='projects.projectfolder'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='projects.projectfolder'),
        ),
    ]
