# Generated by Django 5.2.4 on 2025-09-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_expence_project_folder_alter_income_date_and_more'),
        ('orders', '0023_alter_party_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences', to='orders.party'),
        ),
    ]
