# Generated by Django 5.2.4 on 2025-09-11 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0006_rename_debit_counterparty_debit_usd_and_more'),
        ('finance', '0019_expence_user_income_user'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd')], max_length=3)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expence_contracts', to='counterparty.counterparty')),
                ('expence_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expence_contracts', to='finance.expencetype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expence_contracts', to='projects.project')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expence_contracts', to='projects.projectfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expence_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiqim Shartnomasi',
                'verbose_name_plural': 'Chiqim Shartnomalari',
            },
        ),
        migrations.CreateModel(
            name='IncomeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd')], max_length=3)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contracts', to='counterparty.counterparty')),
                ('income_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contracts', to='finance.typeincome')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contracts', to='projects.project')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_contracts', to='projects.projectfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirim Shartnomasi',
                'verbose_name_plural': 'Kirim Shartnomalari',
            },
        ),
    ]
