# Generated by Django 5.2.4 on 2025-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_expencecontract_incomecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecontract',
            name='paid_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
