# Generated by Django 5.2.4 on 2025-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_incomecontract_paid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencecontract',
            name='paid_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
