# Generated by Django 5.2.4 on 2025-09-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_expencecontract_paid_price'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expencecontract',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expence_contracts', to='projects.projectfolder'),
        ),
    ]
