# Generated by Django 5.2.4 on 2025-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_permission_options_permissiontotab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiontotab',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions_tab',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.permissiontotab'),
        ),
    ]
