# Generated by Django 5.2.4 on 2025-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_permissiontotab_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions_tab',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_tab',
            field=models.ManyToManyField(related_name='permissions', to='accounts.permissiontotab'),
        ),
    ]
