# Generated by Django 5.2.4 on 2025-08-06 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_role_permissions_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionToAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Harakatlar uchun ruxsatnoma',
                'verbose_name_plural': 'Harakatlar uchun ruxsatnomalar',
            },
        ),
        migrations.AddField(
            model_name='permissiontotab',
            name='permission_to_actions',
            field=models.ManyToManyField(related_name='permission_to_tabs', to='accounts.permissiontoaction'),
        ),
    ]
