# Generated by Django 5.2.4 on 2025-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_permissiontoaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_to_actions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.permissiontoaction'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_to_tabs',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.permissiontotab'),
        ),
    ]
