# Generated by Django 5.2.4 on 2025-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_role_permission_to_actions_role_permission_to_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
