# Generated by Django 5.2.4 on 2025-08-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barnch',
            new_name='Branch',
        ),
    ]
