networks:
  uyqur:
    driver: bridge

volumes:
  pg_data: null
  
services:
  nginx:
    networks:
      - uyqur
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
    
  web:
    networks:
      - uyqur
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ${COMMAND:-sh ./resources/scripts/entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - './:/code'
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    networks:
      - uyqur
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    networks:
      - uyqur
    image: redis

