# Generated by Django 5.2.4 on 2025-08-30 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
        ('shared', '0002_usdcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kontragent papkasi',
                'verbose_name_plural': 'Kontragent papkalari',
            },
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='person',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='status',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='balance',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='balance_currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('uzs', 'uzs')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='shared.district'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='shared.region'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('SUPPLIER', "ta'minotchi"), ('WORKER', 'ishchi')], default='SUPPLIER', max_length=20),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='counterparty.counterpartyfolder'),
        ),
    ]
