# Generated by Django 5.2.4 on 2025-09-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0002_counterpartyfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
