# Generated by Django 5.2.4 on 2025-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0003_counterparty_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='status',
            field=models.CharField(choices=[('CREDITOR', 'kreditor'), ('DEBITOR', 'debitor')], default='kreditor', max_length=20),
        ),
    ]
