# Generated by Django 5.2.4 on 2025-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0004_counterparty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='debit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='kredit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
