# Generated by Django 5.2.4 on 2025-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0005_counterparty_debit_counterparty_kredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterparty',
            old_name='debit',
            new_name='debit_usd',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='kredit',
            new_name='debit_uzs',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='kredit_usd',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='kredit_uzs',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='total_debit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='total_kredit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
