# Generated by Django 5.2.4 on 2025-08-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_employee_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderApplication',
        ),
    ]
