# Generated by Django 5.2.4 on 2025-08-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderapplication'),
        ('projects', '0003_alter_project_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='project_department',
        ),
        migrations.AddField(
            model_name='order',
            name='project_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='projects.projectfolder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='projects.project'),
        ),
    ]
