# Generated by Django 5.2.4 on 2025-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_type',
            field=models.CharField(choices=[('UZS', 'uzs'), ('USD', 'usd')], default='uzs'),
        ),
    ]
