# Generated by Django 5.2.4 on 2025-08-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_offer_price_type'),
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='projects.projectfolder'),
        ),
    ]
