# Generated by Django 5.2.4 on 2025-08-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
        ('orders', '0007_alter_order_project_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='offer',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='counterparty.counterparty'),
        ),
    ]
