# Generated by Django 5.2.4 on 2025-08-21 10:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_counterparty_order_currency_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='coled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='party',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='payment_status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='process',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.CharField(blank=True, choices=[('ORDERED', 'yetkazildi'), ('PROCESS', 'jarayonda')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PartyAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.PositiveBigIntegerField()),
                ('cost_amount', models.PositiveBigIntegerField(default=0)),
                ('calculated_amount', models.PositiveBigIntegerField(default=0)),
                ('paid_amount', models.PositiveBigIntegerField(default=0)),
                ('payment_amount', models.BigIntegerField(default=0)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_amount', to='orders.party')),
            ],
            options={
                'verbose_name': 'Partiya Summasi',
                'verbose_name_plural': 'Partiya summalari',
            },
        ),
    ]
