# Generated by Django 5.2.4 on 2025-08-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_party_coled_date_party_confirmation_party_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='coled_date',
            new_name='closed_date',
        ),
    ]
