# Generated by Django 5.2.4 on 2025-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_coled_date_party_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='qqs_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
