# Generated by Django 5.2.4 on 2025-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_party_discount_party_qqs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qqs_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='payment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='payment_status',
            field=models.CharField(choices=[('PAID', "to'langan"), ('PARTIALLY', 'qisman'), ('NOT_PAID', "to'lanmagan"), ('OVERPAID', "ortiqcha to'langan")], default='NOT_PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(choices=[('NEW', 'yangi'), ('PARTY_IS_MADE', 'partiya qilingan'), ('EXPECTED', 'kutilmoqda'), ('DRAFT', 'qoralama'), ('CANCELLED', 'bekor qilingan'), ('PURCHASED', 'sotib olinmoqda'), ('PROCESS', 'jarayonda')], default='NEW', max_length=20),
        ),
    ]
