# Generated by Django 5.2.4 on 2025-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_qqs_price_party_payment_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
