# Generated by Django 5.2.4 on 2025-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='qqs_price',
            new_name='qqs',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
