# Generated by Django 5.2.4 on 2025-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_qqs_price_party_qqs_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='qqs',
        ),
        migrations.AddField(
            model_name='order',
            name='qqs',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
