# Generated by Django 5.2.4 on 2025-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_party_qqs_order_qqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='confirmation',
            field=models.CharField(choices=[('EXPECTED', 'kutilmoqda'), ('APPROVER', 'tasdiqlangan'), ('REJECTED', 'rad etilgan')], default='EXPECTED', max_length=20),
        ),
    ]
