# Generated by Django 5.2.4 on 2025-08-22 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_party_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeletedParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_parties', to='orders.party')),
            ],
            options={
                'verbose_name': "O'chirilgan partiya",
                'verbose_name_plural': "O'chirilgan partiyalar",
            },
        ),
    ]
