# Generated by Django 5.2.4 on 2025-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_party_is_deleted_deletedparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedparty',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
