# Generated by Django 5.2.4 on 2025-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_deletedparty_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='discount_currency',
            field=models.CharField(blank=True, choices=[('uzs', 'uzs'), ('usd', 'usd')], default='uzs', max_length=3, null=True),
        ),
    ]
