# Generated by Django 5.2.4 on 2025-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_party_discount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('uzs', 'uzs')], default='uzs', max_length=3),
        ),
    ]
