# Generated by Django 5.2.4 on 2025-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_party_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
