# Generated by Django 5.2.4 on 2025-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_party_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='parties', to='orders.order'),
        ),
    ]
