# Generated by Django 5.2.4 on 2025-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_folder_product_product_code_product_unity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MECHANISM', 'maxanizm'), ('PRODUCT', 'mahsulot'), ('HUMAN_RESOURCE', 'inson resursi'), ('SERVICE', 'xizmat')], default='TANGIBLE', max_length=20),
        ),
    ]
