# Generated by Django 5.2.4 on 2025-08-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfolder_project_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectfolder'),
        ),
    ]
