# Generated by Django 5.2.4 on 2025-08-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_project_department_order_project_folder_and_more'),
        ('projects', '0003_alter_project_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDepartment',
        ),
    ]
