# Generated by Django 5.2.4 on 2025-08-04 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0004_delete_projectdepartment'),
        ('wherehouse', '0002_stockmovemend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Quruvchi',
                'verbose_name_plural': 'Quruvchilar',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='benifit_plan',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='boss',
            field=models.ManyToManyField(related_name='project_bosses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='cash_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='finance.cashtransaction'),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('uzs', 'uzs')], default='uzs', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ManyToManyField(related_name='project_foremans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='other_members',
            field=models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='wherehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='wherehouse.wherehouse'),
        ),
        migrations.AddField(
            model_name='project',
            name='builder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.builder'),
        ),
    ]
