# Generated by Django 5.2.4 on 2025-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymenttype_cashtransaction_employees_and_more'),
        ('projects', '0005_builder_project_area_project_benifit_plan_and_more'),
        ('wherehouse', '0002_stockmovemend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cash_transaction',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wherehouse',
        ),
        migrations.AddField(
            model_name='project',
            name='cash_transaction',
            field=models.ManyToManyField(null=True, related_name='projects', to='finance.cashtransaction'),
        ),
        migrations.AddField(
            model_name='project',
            name='wherehouse',
            field=models.ManyToManyField(related_name='projects', to='wherehouse.wherehouse'),
        ),
    ]
