# Generated by Django 5.2.4 on 2025-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymenttype_cashtransaction_employees_and_more'),
        ('projects', '0006_remove_project_cash_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cash_transaction',
            field=models.ManyToManyField(related_name='projects', to='finance.cashtransaction'),
        ),
    ]
