# Generated by Django 5.2.4 on 2025-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_cash_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfolder',
            name='color',
            field=models.CharField(choices=[('ORANGE', 'orange'), ('GREEN', 'green'), ('BLUE', 'blue'), ('PURPLE', 'purple'), ('RED', 'red')], default='ORANGE', max_length=10),
        ),
    ]
