# Generated by Django 5.2.4 on 2025-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectfolder_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'planned'), ('IN_PROGRESS', 'in progress'), ('FINISHED', 'finished'), ('SUSPENDED', 'suspended')], default='PLANNED', max_length=20),
        ),
    ]
