# Generated by Django 5.2.4 on 2025-08-07 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_status'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='shared.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='shared.region')),
            ],
            options={
                'verbose_name': 'Loyiha lokatsiyasi',
                'verbose_name_plural': 'Loyiha lokatsiyalari',
            },
        ),
    ]
