# Generated by Django 5.2.4 on 2025-08-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectlocation'),
        ),
    ]
