# Generated by Django 5.2.4 on 2025-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectestimate_estimateproduct_estimatework'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatework',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='benifit_plan',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
