# Generated by Django 5.2.4 on 2025-08-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_estimatework_total_price_alter_project_benifit_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateproduct',
            name='estimate_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_products', to='projects.estimatework'),
        ),
    ]
