# Generated by Django 5.2.4 on 2025-08-14 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_estimateproduct_estimate_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatework',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='estimate_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimatework',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatework',
            name='percentage',
            field=models.PositiveSmallIntegerField(blank=True, db_default=0, null=True),
        ),
        migrations.AddField(
            model_name='estimatework',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatework',
            name='status',
            field=models.CharField(choices=[('OPEN', 'ochiq'), ('IN_PROGRESS', 'bajarilmoqda'), ('DONE', 'bajarildi')], default='ochiq', max_length=20),
        ),
    ]
