# Generated by Django 5.2.4 on 2025-08-01 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('wherehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovemend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('movemend_type', models.CharField(choices=[('IN', 'in'), ('OUT', 'out'), ('TRANSFER', 'transfer')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product')),
                ('wherehouse_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_from', to='wherehouse.wherehouse')),
                ('wherehouse_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_to', to='wherehouse.wherehouse')),
            ],
            options={
                'verbose_name': 'Mahsulotlarni kochirish',
                'verbose_name_plural': 'Mahsulotlarni kochirish',
            },
        ),
    ]
