# Generated by Django 5.2.4 on 2025-08-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_type'),
        ('wherehouse', '0002_stockmovemend'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='products.unity'),
        ),
    ]
