# Generated by Django 5.2.4 on 2025-08-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
        ('wherehouse', '0003_inventory_price_inventory_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='projects.project'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='projects.projectfolder'),
        ),
    ]
