# Generated by Django 5.2.4 on 2025-08-26 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
        ('wherehouse', '0004_inventory_project_inventory_project_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('BROKEN', 'singan'), ('LOST', 'yoqolgan'), ('OTHER', 'boshqa')], default='other', max_length=20)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comment', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='invalid_product/files/')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalid_products', to='wherehouse.inventory')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalid_products', to='projects.projectfolder')),
                ('witnesses', models.ManyToManyField(related_name='invalid_products', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalid_products', to='projects.estimatework')),
            ],
            options={
                'verbose_name': 'yaroqsiz maxsulot',
                'verbose_name_plural': 'yaroqsiz maxsulotlar',
            },
        ),
    ]
