# Generated by Django 5.2.4 on 2025-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0005_invalidproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
