# Generated by Django 5.2.4 on 2025-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0006_inventory_is_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
