# Generated by Django 5.2.4 on 2025-08-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0007_inventory_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidproduct',
            name='invalid_status',
            field=models.CharField(choices=[('BROKEN', 'singan'), ('LOST', 'yoqolgan'), ('OTHER', 'boshqa')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='invalidproduct',
            name='wherehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invalid_products', to='wherehouse.wherehouse'),
        ),
        migrations.AlterField(
            model_name='invalidproduct',
            name='status',
            field=models.CharField(choices=[('OPEN', 'ochiq'), ('EXPECTED', 'kutilmoqda'), ('ACCEPTED', 'qabul qilingan'), ('CANCELLED', 'bekor qilingan')], default='OPEN', max_length=20),
        ),
    ]
