# Generated by Django 5.2.4 on 2025-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0008_invalidproduct_invalid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidproduct',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
