# Generated by Django 5.2.4 on 2025-08-28 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_type'),
        ('wherehouse', '0009_alter_invalidproduct_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovemend',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovemend',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movmends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovemend',
            name='movemend_type',
            field=models.CharField(choices=[('EXPECTED', 'kutilmoqda'), ('ACCEPTED', 'qabul qilingan'), ('CANCELLED', 'bekor qilingan')], default='EXPECTED', max_length=20),
        ),
        migrations.CreateModel(
            name='StockMovmendProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movmend_products', to='products.product')),
                ('stock_movemend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movmend_products', to='wherehouse.stockmovemend')),
                ('unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unity')),
            ],
            options={
                'verbose_name': "Ko'chirilgan mahsulot",
                'verbose_name_plural': "Ko'chirilgan mahsulotlar",
            },
        ),
    ]
