# Generated by Django 5.2.4 on 2025-08-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
        ('wherehouse', '0010_remove_stockmovemend_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovmendproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovmendproduct',
            name='unity',
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movmends', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stockmovemend',
            name='project_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movmends', to='projects.projectfolder'),
        ),
        migrations.AddField(
            model_name='stockmovmendproduct',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movmend_products', to='wherehouse.inventory'),
        ),
    ]
