# Generated by Django 5.2.4 on 2025-08-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_estimatework_employee_estimatework_end_date_and_more'),
        ('wherehouse', '0012_alter_stockmovemend_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovemend',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movmends', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='stockmovemend',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movmends', to='projects.projectfolder'),
        ),
    ]
