# Generated by Django 5.2.4 on 2025-08-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0013_alter_stockmovemend_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovemend',
            name='file',
        ),
    ]
