# Generated by Django 5.2.4 on 2025-08-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wherehouse', '0014_remove_stockmovemend_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovmendproduct',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movemend_products', to='wherehouse.inventory'),
        ),
        migrations.AlterField(
            model_name='stockmovmendproduct',
            name='stock_movemend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movemend_products', to='wherehouse.stockmovemend'),
        ),
    ]
